spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 62556609
mybatis:
  mapper-locations:
    -classpath: mapper/*.xml
    -classpath*: com/**/mapper/*.xml

